'use client';
import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { chemistryPaymentLink, creatorPosts, masterclass, priceLabel, socials, site } from '@/data/site';

const nav = [['Masterclasses','/masterclasses'],['Community','/community'],['Resources','/resources'],['Tutoring','/tutoring'],['About','/about']];
function NavArrow(){return <svg className="nav-arrow" viewBox="0 0 20 20" width="20" height="20" fill="none" aria-hidden="true"><path d="M4.5 15.5 15.5 4.5M7 4.5h8.5V13" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function SectionLabel({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }
export function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="wrap nav-inner"><Link className="logo" href="/" onClick={() => setOpen(false)} aria-label="The Study Verse home"><span className="logo-icon" aria-hidden="true"><Image src="/favicon.svg" alt="" width={36} height={36} priority /></span><span className="logo-wordmark"><span>THE</span><strong>Study Verse</strong></span></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><div className="nav-actions"><a href={socials.discord} target="_blank" rel="noopener noreferrer" className="nav-pill">Join Discord ↗</a></div><button className="menu-toggle" type="button" aria-expanded={open} aria-controls="mobile-menu" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? 'Close' : 'Menu'} <span aria-hidden="true">{open ? '↑' : '↓'}</span></button></div><nav id="mobile-menu" className={open ? 'mobile-nav open' : 'mobile-nav'} aria-label="Mobile navigation">{nav.map(([label,href])=><Link key={href} href={href} onClick={() => setOpen(false)}>{label}<NavArrow /></Link>)}<Link href="/masterclasses/gcse-chemistry" onClick={() => setOpen(false)}>GCSE Chemistry <NavArrow /></Link><a href={socials.discord} target="_blank" rel="noopener noreferrer" onClick={() => setOpen(false)}>Join Discord <NavArrow /></a></nav></header>;
}
export function Footer() {
  return <footer className="site-footer"><div className="wrap"><div className="footer-lead"><Image className="footer-brand" src="/logo-light.svg" alt="The Study Verse" width={190} height={38} /><h2>Keep going.<br /><em>We&apos;re with you.</em></h2><a href={`mailto:${site.email}`}>{site.email} ↗</a></div><div className="footer-columns"><div><small>EXPLORE</small>{[['Masterclasses','/masterclasses'],['Community','/community'],['TSV VIP','/vip'],['Courses','/courses'],['Resources','/resources'],['Tutoring','/tutoring'],['About','/about'],['Contact','/contact']].map(([n,h])=><Link href={h} key={h}>{n}</Link>)}</div><div><small>FOLLOW ASH</small>{[['TikTok',socials.tiktok],['Instagram',socials.instagram],['YouTube',socials.youtube],['Discord',socials.discord]].map(([n,h])=><a href={h} key={h} target="_blank" rel="noopener noreferrer">{n} ↗</a>)}</div><div><small>INFORMATION</small>{[['Privacy','/privacy'],['Terms','/terms'],['Refunds','/refunds'],['Cookies','/cookies']].map(([n,h])=><Link href={h} key={h}>{n}</Link>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} THE STUDY VERSE</span><span>BUILT BY STUDENTS, FOR STUDENTS.</span><a href="#main">BACK TO TOP ↑</a></div></div></footer>;
}
export function BrandArtwork() { return <div className="brand-artwork" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><span className="art-star">✳</span><span className="art-word">STUDY<br />VERSE</span><div className="art-coordinate">TSV © 2026<br />BETTER TOGETHER</div></div>; }
export function CommunityPreview() { return <div className="community-preview"><div className="community-image"><Image src="/assets/discord-banner.png" alt="The Study Verse Discord server banner" fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div className="community-image-caption"><Image src="/assets/discord-icon.png" alt="" width={58} height={58}/><div><strong>THE STUDY VERSE</strong><span>DISCORD COMMUNITY · EST. OCT 2025</span></div><span>↗</span></div></div>; }
export function CreatorMedia() { return <div className="creator-media"><div className="creator-photo"><Image src="/assets/ash-hours-frame.jpg" alt="Ash speaking to camera in his study video" fill sizes="(max-width: 760px) 100vw, 44vw" /></div><span>ASH / 4ZHFN · CREATOR</span></div>; }
export function CreatorGallery() { return <div className="creator-gallery"><div className="video-grid"><figure><video controls preload="metadata" playsInline poster="/assets/ash-study-frame.jpg" src="/assets/tiktok-1.mp4" aria-label="Ash studying at a desk"><track kind="captions" src="/assets/tiktok-1.vtt" srcLang="en" label="English" /></video><figcaption>01 / Showing up to study</figcaption></figure><figure><video controls preload="metadata" playsInline poster="/assets/ash-hours-frame.jpg" src="/assets/tiktok-2.mp4" aria-label="Ash's study hours video"><track kind="captions" src="/assets/tiktok-2.vtt" srcLang="en" label="English" /></video><figcaption>02 / The hours behind it</figcaption></figure></div><div className="post-list"><span className="eyebrow">EXPLORE THE ORIGINAL POSTS</span>{creatorPosts.map((post,i)=><a href={post.href} key={post.href} target="_blank" rel="noopener noreferrer"><span>0{i+1}</span><strong>{post.label}</strong><small>{post.platform} ↗</small></a>)}</div></div>; }
export function NewsletterForm({ enabled }: { enabled: boolean }) {
  const [state,setState] = useState<'idle'|'loading'|'success'|'error'>('idle');
  const [message,setMessage] = useState('');
  async function submit(e: React.SyntheticEvent<HTMLFormElement>) { e.preventDefault(); const form=e.currentTarget; const fd=new FormData(form); setState('loading'); try { const r=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'), consent:fd.get('consent')==='on'})}); const d=await r.json(); if(!r.ok) throw new Error(d.error || 'Please try again.'); setState('success'); setMessage('You’re on the list. See you in your inbox.'); form.reset(); } catch(err) {setState('error');setMessage(err instanceof Error ? err.message : 'Please try again.');} }
  if (!enabled) return <div className="booking-soon"><strong>Email updates open soon</strong><span>We are setting up the list. Check back shortly or follow Ash for announcements.</span></div>;
  return <form className="newsletter-form" onSubmit={submit}><label htmlFor="newsletter-email">Your email address</label><div className="input-row"><input id="newsletter-email" name="email" type="email" placeholder="you@example.com" autoComplete="email" required/><button type="submit" disabled={state==='loading'}>{state==='loading'?'Joining…':'Join the list ↗'}</button></div><label className="consent"><input type="checkbox" name="consent" required/><span>I agree to receive occasional updates from The Study Verse. Unsubscribe any time.</span></label><output className="form-status">{message}</output></form>;
}
export function BookingButton({ className = '' }: { className?: string }) {
  if (masterclass.status === 'scheduled') return <a className={`button button-dark ${className}`} href={chemistryPaymentLink} target="_blank" rel="noopener noreferrer">Reserve your place · {priceLabel()} ↗</a>;
  return <div className="booking-soon"><strong>{masterclass.status === 'sold-out' ? 'All places booked' : 'Booking opens soon'}</strong><span>Join the update list to hear when places become available.</span><Link href="/#newsletter">Get updates ↗</Link></div>;
}
