import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { NewsletterForm, SectionLabel } from '@/components/tsv';
import { site, socials, legal } from '@/data/site';
const pages = {
  vip: { title: 'TSV VIP', eyebrow: 'A CLOSER CIRCLE', intro: 'A premium Study Verse membership is in development. The VIP area already has a place in our Discord; membership details are coming soon.', description: 'We are shaping what TSV VIP becomes with the community. Pricing and specific benefits will be shared only when they are confirmed.' },
  courses: { title: 'Courses', eyebrow: 'COMING NEXT', intro: 'More room to go deep. Study Verse courses are in development.', description: 'We are working towards structured learning that students can return to in their own time. The first details will be announced here and by email.' },
  resources: { title: 'Resources', eyebrow: 'REVISION, MADE USEFUL', intro: 'Practical revision resources are on the way.', description: 'We want every resource to earn its place on your desk. PDFs, exam practice and study tools will appear here as they are ready.' },
  tutoring: { title: 'Tutoring', eyebrow: 'MORE PERSONAL SUPPORT', intro: 'Tutoring and 1-to-1 sessions are planned for The Study Verse.', description: 'Availability, subjects, teaching team and pricing are still being confirmed. For an enquiry, contact Ash directly.' },
} as const;
type Slug = keyof typeof pages;
const policies = ['privacy','terms','refunds','cookies'] as const;
export function generateStaticParams(){ return [...Object.keys(pages),'contact',...policies].map(slug=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const title=slug in pages?pages[slug as Slug].title:slug==='contact'?'Contact':slug==='refunds'?'Refunds and cancellations':slug[0].toUpperCase()+slug.slice(1);return {title,alternates:{canonical:`/${slug}`},description:`${title} at The Study Verse.`};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(slug in pages){const p=pages[slug as Slug];return <><section className="page-hero wrap"><SectionLabel>{p.eyebrow}</SectionLabel><h1>{p.title}<em>.</em></h1><p>{p.intro}</p></section><section className="page-section"><div className="wrap two-col"><div><SectionLabel>IN THE WORKS</SectionLabel><h2>Good things take shape.</h2></div><div><p>{p.description}</p>{slug==='tutoring'?<Link className="button button-dark" href="/contact">Ask about tutoring ↗</Link>:slug==='vip'?<a className="button button-dark" href={socials.discord} target="_blank" rel="noopener noreferrer">Join the Discord ↗</a>:<Link className="button button-dark" href="/masterclasses/gcse-chemistry">Explore our first masterclass ↗</Link>}</div></div></section><section className="newsletter-section" id="newsletter"><div className="wrap newsletter-grid"><div><SectionLabel>HEAR IT FIRST</SectionLabel><h2>Stay in<br /><em>the loop.</em></h2><p>One or two useful emails a month. No daily spam.</p></div><NewsletterForm enabled={Boolean(process.env.RESEND_API_KEY && (process.env.RESEND_SEGMENT_ID || process.env.RESEND_AUDIENCE_ID))} /></div></section></>;}
if(slug==='contact')return <><section className="page-hero wrap"><SectionLabel>GET IN TOUCH</SectionLabel><h1>Say <em>hello.</em></h1><p>Questions about the masterclass, the community, tutoring or a collaboration? Write to Ash.</p></section><section className="page-section"><div className="wrap"><h2><a href={`mailto:${site.email}`}>{site.email} ↗</a></h2><p>We read messages about general enquiries, masterclasses, tutoring and collaborations at this address.</p></div></section></>;
if(!policies.includes(slug as typeof policies[number]))notFound();
return <section className="page-hero wrap policy"><SectionLabel>THE STUDY VERSE / INFORMATION</SectionLabel><h1>{slug==='refunds'?'Refunds & cancellations':slug[0].toUpperCase()+slug.slice(1)}<em>.</em></h1><div className="notice">Draft for business and legal review. Last reviewed {legal.lastReviewed}. For questions, email <a href={`mailto:${site.email}`}>{site.email}</a>.</div>{slug==='privacy'?<><h2>What we collect</h2><p>If you join the email list, we collect your email address and your consent choice. If you book a masterclass, Stripe handles payment information and sends us the details needed to manage your booking. We do not collect card details on this site.</p><h2>How we use it</h2><p>We use booking information to deliver the session and respond to support requests. Marketing emails are sent only after you actively opt in, and you can unsubscribe using the link in each email.</p><h2>Questions and requests</h2><p>Contact {site.email} to ask about your information or request removal. Provider records needed for payment, accounting or legal obligations may be retained as required.</p></>:slug==='terms'?<><h2>Using the site</h2><p>Content is provided for study support and general information. We aim to keep it accurate, but course details and availability may change before booking opens.</p><h2>Masterclasses</h2><p>Confirmed booking terms, dates, presenter and delivery details will be shown before payment. Access information is provided privately to attendees. Please do not share private joining details or distribute session materials without permission.</p><h2>Contact</h2><p>For any concern about a purchase or the site, contact {site.email}. Final business terms will be reviewed before paid bookings launch.</p></>:slug==='refunds'?<><h2>Before booking</h2><p>The Chemistry masterclass timing is provisional and booking is not yet open. The final cancellation and refund terms will be published before payment is enabled.</p><h2>If plans change</h2><p>If we cancel a paid live session, we will contact affected customers with a suitable resolution. If you have a booking question or need to discuss a cancellation, email {site.email} with your order details.</p><h2>Your rights</h2><p>This draft does not limit any rights that apply under consumer law. Final wording needs business and legal review before sales launch.</p></>:<><h2>Essential operation</h2><p>This site does not currently load advertising trackers or non-essential analytics. Stripe may set cookies as part of its secure checkout if booking is enabled.</p><h2>Choices</h2><p>We will add a consent control if we introduce non-essential cookies in the future. You can manage existing cookies in your browser settings.</p></>}</section>;
}
